[project]
name = 'Blockchain-Based-Manufacturing-Digital-Thread'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.design-verification]
path = 'contracts/design-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.lifestyle-tracking]
path = 'contracts/lifestyle-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-tracking]
path = 'contracts/material-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.preocess-parameters]
path = 'contracts/preocess-parameters.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-verification]
path = 'contracts/quality-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
